### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by marceloverdijk** [jkutner/graal-buildpack#1]
Hi @jkutner is this still the "official" way to run Graal on Heroku?
I'm wondering as this repo is not updated anymore and it uses Graal 1.0.0-rc4..

**Comment by jkutner** [comment]
@marceloverdijk there is no "official" way to run Graal on Heroku (i.e. it's not officially supported by Heroku). But buildpacks are meant to allow you to run whatever you'd like. You can either fork this buildpack to update Graal, or I'll accept a PR.

**Comment by marceloverdijk** [comment]
Understood @jkutner I was currently reading about Graal and was wondering if there will be official support to use it on Heroku in the future?

**Comment by jkutner** [comment]
No plans at this time

**Comment by marceloverdijk** [comment]
OK thx! Let's close this one for now.
